exclude: (^\.pre-commit-config\.yaml$)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v5.0.0"
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    exclude: .clang-format
    args: ['--unsafe']
  - id: check-ast
  - id: check-docstring-first
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: (^.*\.cs$|^.*\.csproj$|^.*\.sln$)
  - id: mixed-line-ending
    exclude: (^.*\.cs$|^.*\.csproj$|^.*\.sln$)
  - id: trailing-whitespace
  - id: fix-byte-order-marker
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: check-xml
  - id: detect-private-key
  - id: no-commit-to-branch
    args: ['--branch', 'master']
  - id: forbid-submodules
- repo: https://gitlab.com/bmares/check-json5
  rev: v1.0.0
  hooks:
  - id: check-json5
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2', '--preserve-quotes']
    exclude: ^\.clang.*$
# - repo: https://github.com/efrecon/pre-commit-hook-lxml
#   rev: v0.1.1
#   hooks:
#   - id: format-xml
#     exclude: ^.*\.svg$
- repo: local
  hooks:
  - id: dos2unix
    name: dos2unix
    entry: dos2unix
    args: ["-n", "-o"]
    files: '\.(c|cpp|h|hpp|java|i|m|cmake|txt|css|js|ts|html|md|txt|py|yaml|yml|rst|py\.in|)$'
    language: system
-   repo: local
    hooks:
    #Use dotnet format already installed on your machine
    -   id: dotnet-format
        name: dotnet-format
        language: system 
        entry: dotnet format --include 
        types_or: ["c#", "vb"]

