//This file is automatically generated. DO NOT EDIT!
using System;
using RobotRaconteur;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 0108

namespace com.robotraconteur.testing.TestService2
{
[RobotRaconteurServiceStruct("com.robotraconteur.testing.TestService2.ostruct2")]
public class ostruct2
{
    public double[] a1;
}

[RobotRaconteurServiceObjectInterface("com.robotraconteur.testing.TestService2.baseobj")]
public interface baseobj
{
    Task<double> get_d1(CancellationToken cancel=default(CancellationToken));
    Task set_d1(double value, CancellationToken cancel=default(CancellationToken));
    Task<double[]> get_d2(CancellationToken cancel=default(CancellationToken));
    Task set_d2(double[] value, CancellationToken cancel=default(CancellationToken));
    Task<double> func3(double d1, double d2,CancellationToken rr_cancel=default(CancellationToken));
    event Action ev1;
    Task<subobj> get_o5(CancellationToken rr_cancel=default(CancellationToken));
    Pipe<double[]> p1{ get; set; }
    Callback<Func<double, double, CancellationToken, Task>> cb2 {get; set;}
    Wire<double[]> w1 { get; set; }
    ArrayMemory<double> m1 { get; }
}

[RobotRaconteurServiceObjectInterface("com.robotraconteur.testing.TestService2.subobj")]
public interface subobj
{
    Task<double> add_val(double v,CancellationToken rr_cancel=default(CancellationToken));
}

public class testexception3 : RobotRaconteurRemoteException
{
    public testexception3(string message) : base("com.robotraconteur.testing.TestService2.testexception3",message) {}
};
}
