//This file is automatically generated. DO NOT EDIT!
using System;
using RobotRaconteurWeb;
using RobotRaconteurWeb.Extensions;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 0108

namespace experimental.wire_sub_test
{
[RobotRaconteurServiceObjectInterface("experimental.wire_sub_test.testobj")]
public interface testobj
{
    Task<testobj2> get_subobj(CancellationToken rr_cancel=default(CancellationToken));
    Wire<double> testwire1 { get; set; }
    Wire<double> testwire2 { get; set; }
}

[RobotRaconteurServiceObjectInterface("experimental.wire_sub_test.testobj2")]
public interface testobj2
{
    Wire<double> testwire3 { get; set; }
}

}
