name: docs

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet 3.1.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x
      - name: Install dependencies
        run: dotnet restore
      - name: Install H5
        run: dotnet tool update --global h5-compiler
      - name: Install docfx
        run: dotnet tool update -g docfx
      - name: Build docs 
        working-directory: ./docs/netcore
        run: docfx
      - name: tree
        run: tree  /a /f
      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: robotraconteurweb-docfx
          path: |
            ./docs/netcore/_site/