name: CI

on:
  push:
  pull_request:
  release:
    types:
    - created

  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet 8.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Install dependencies
      run: dotnet restore
    - name: Install H5
      run: dotnet tool update --global h5-compiler
    - name: Run
      run: dotnet run --project RobotRaconteurWebTest/RobotRaconteurWebTest.csproj --configuration Release
      shell: cmd
    - name: Build nuget packages
      run: |
        dotnet pack  "RobotRaconteurWeb/RobotRaconteurWeb.csproj" -p:Platform="AnyCPU" --configuration Release
        dotnet pack  "RobotRaconteurWebGen/RobotRaconteurWebGen.csproj" -p:Platform="AnyCPU" --configuration Release
        dotnet pack  "RobotRaconteurH5/RobotRaconteurH5.csproj" -p:Platform="AnyCPU" --configuration Release
    - name: Upload nuget packages
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: |
          ./**/*.nupkg
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet 8.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Build and Run
      run: dotnet run --project RobotRaconteurWebTest/RobotRaconteurWebTest.csproj --configuration Release
  pre-commit:
    runs-on: ubuntu-latest
    env:
      SKIP: no-commit-to-branch
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: apt
      run: |
        sudo apt update
        sudo apt install -y dos2unix
    - name: Setup dotnet 8.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - uses: pre-commit/action@v3.0.1
